# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKoGjDaiTqvYlPA11J4yjuYQVNN1L1X-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error
df = pd.read_csv("/Users/ayush/Downloads/Consumer Price Index_Sample_Data.csv")

print("Dataset Loaded\n")
print(df.head())

df.rename(columns={
    'Year (date)': 'Date',
    'State Name (state_name)': 'State',
    'State Code (state_code)': 'State_Code',
    'Commodity Group (commodity_group)': 'Commodity',
    'Sector (sector)': 'Sector',
    'Consumer Price Index (cpi)': 'CPI',
    'Inflation Rate (inflation_rate)': 'Inflation'
}, inplace=True)

print("\nColumns after renaming:")
print(df.columns)

df['Date'] = pd.to_datetime(df['Date'])
df = df.dropna()

print(df.isnull().sum())

df = df.sort_values('Date')
# Time features
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Quarter'] = df['Date'].dt.quarter

# Encode categorical variables
df['Sector_Code'] = df['Sector'].astype('category').cat.codes
df['Commodity_Code'] = df['Commodity'].astype('category').cat.codes

df['Lag_CPI'] = df['CPI'].shift(1)
df = df.dropna()

print("\nFeature Engineering Completed")
print(df.head())

yearly = df.groupby('Year')['CPI'].mean()

plt.figure(figsize=(10,5))
plt.plot(yearly.index, yearly.values)
plt.title("CPI Trend Over Time")
plt.xlabel("Year")
plt.ylabel("CPI")
plt.show()

sector_trend = df.groupby(['Year','Sector'])['CPI'].mean().unstack()
sector_trend.plot(figsize=(10,5))
plt.title("Urban vs Rural CPI Trend")
plt.ylabel("CPI")
plt.show()

state_avg = df.groupby('State')['CPI'].mean().sort_values()
state_avg.plot(kind='barh')
plt.title("Average CPI by State")
plt.show()

print("High-cost and high-volatility states identified.")
plt.figure(figsize=(10,8))

# Scatter plot
# State-level statistics
state_stats = df.groupby('State')['CPI'].agg(['mean','std'])

print(state_stats.head())

plt.scatter(state_stats['mean'], state_stats['std'])
plt.axhline(state_stats['std'].mean(), linestyle='--')
plt.axvline(state_stats['mean'].mean(), linestyle='--')
for s in state_stats.index:
    plt.annotate(
        s,
        (state_stats.loc[s, 'mean'], state_stats.loc[s, 'std'])
        )
# Labels
plt.xlabel("Average CPI")
plt.ylabel("Volatility (Std Dev)")
plt.title("Cost–Stability Quadrant")
plt.grid()
plt.show()

corr_cols = ['CPI','Inflation','Year','Month','Quarter','Lag_CPI']
plt.figure(figsize=(8,6))
sns.heatmap(df[corr_cols].corr(), annot=True)
plt.title("Correlation Matrix")
plt.show()

features = [
    'Year',
    'Month',
    'Quarter',
    'State_Code',
    'Sector_Code',
    'Commodity_Code',
    'Inflation',
    'Lag_CPI'
]

X = df[features].apply(pd.to_numeric)
y = df['CPI']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42)

model.fit(X_train, y_train)

pred = model.predict(X_test)
r2 = r2_score(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))
print("\nModel Performance:")
print("R²:", r2)
print("RMSE:", rmse)

future = pd.DataFrame({
    'Year':[2026],
    'Month':[12],
    'Quarter':[4],
    'State_Code':[df['State_Code'].mode()[0]],
    'Sector_Code':[df['Sector_Code'].mode()[0]],
    'Commodity_Code':[df['Commodity_Code'].mode()[0]],
    'Inflation':[df['Inflation'].mean()],
    'Lag_CPI':[df['CPI'].iloc[-1]]
})

future = future.apply(pd.to_numeric)

future_pred = model.predict(future)

print("\nPredicted CPI for 2026:", future_pred[0])
plt.figure(figsize=(10,5))

plt.plot(yearly.index, yearly.values, label='Historical CPI')

plt.scatter(2026, future_pred[0], color='red', label='Predicted 2026 CPI')

plt.legend()
plt.title("CPI Forecast (2026)")

plt.show()